apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-stateful
  labels:
    app: mongodb_mails
spec:
  serviceName: mongo-stateful
  replicas: 2
  selector:
    matchLabels:
      app: mongodb_mails
  template:
    metadata:
      labels:
        app: mongodb_mails
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb-mails
          image: mongo:5.0.9
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 250m
              memory: 200Mi
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-mails-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-mails-secret
                  key: mongo-root-password
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: "standard"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 150Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
#  labels:
#    app: mongodb_mails
spec:
  clusterIP: None
  selector:
    app: mongodb_mails
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017