version: "3.8"
services:
  api-server:
    build: .
    container_name: mail-sender-api
    ports:
      - 8080:8080
    environment:
      - MONGODB_CONNSTRING=mongodb://alim:123456@mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongo-dev
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
#    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongo-dev

volumes:
  data: { }

networks:
  default:
    name: mongodb_network